### ISSUE TITLE
Option examples

### ISSUE THREAD

**Issue by amqex** [MatTheCat/HtmlCompressorBundle#1]
Hello,

I installed the bundle but I wasn't able to get the html output compressed. I tried different options from the htmlcompressor documentation. Maybe I'm not using it correctly.

```
options: { '--type': html  }
```

Does the bundle name have to be provided? Can you provide an example for compressing html output?

Thanks!

**Comment by MatTheCat** [comment]
Hi!

In theory you don't have to specifiy any option, are you sure your responses are cacheable? As the compression process is somewhat heavy I avoided to launch it for every request.

I could change this behaviour but to be honest I think the time needed to compress the output make this bundle useless for production. It is my first bundle you see ^^'
