### ISSUE TITLE
update symfony required version

### ISSUE THREAD

**Issue by vihuvac** [MatTheCat/HtmlCompressorBundle#3]
Hello @MatTheCat how are you?

Is there any way to update the **_symfony required version**_ in order to make it work under **_symfony 2**_ and **_symfony 3**_? It'd look like:

```
...
"require": {
    "php": ">=5.3.0",
    "symfony/symfony": "~2|~3"
},
...
```

I am going to be waiting for updates about it.

Thanks a lot beforehand!

**Comment by MatTheCat** [comment]
Hi!

I don't think I'll update this bundle. [As you saw too](https://github.com/MatTheCat/HtmlCompressorBundle/issues/2) it is a wrong approach of the HTML minification problem.

I wrote a [twig extension](https://github.com/MatTheCat/twig-whitespace-collapse-extension) instead (see http://www.matthecat.com/minifier-votre-html-avec-twig/).

**Comment by vihuvac** [comment]
Hi @MatTheCat,

This bundle is working fine for me under **_symfony 2.x**_ but I cannot keep using it in **_symfony 3**_ due to the required framework version inside the **_composer.json**_ file:

```
...
"symfony/symfony": "2.*"
...
```

Regarding to the missing file `compiler.jar` I can add it!

**Comment by MatTheCat** [comment]
You shouldn't be using this bundle whichever the Symfony version. As I said it implements a _wrong_ approach and I provided [a better one](https://github.com/MatTheCat/twig-whitespace-collapse-extension), so I won't update it.

If you want to keep the overhead of a Java process on every request feel free to update your fork.

**Comment by vihuvac** [comment]
Oh ok ok, I'll take a look at the new twig extension.

Thank you very much.

:+1:
