### ISSUE TITLE
Symfony3 compatibility 

### ISSUE THREAD

**Issue by pesseyjulien** [MatTheCat/HtmlCompressorBundle#4]
Hi,

Is the compatibility for Symfony 3 planned ?

Thanks,
Julien

**Comment by MatTheCat** [comment]
Hi,

https://github.com/MatTheCat/HtmlCompressorBundle/issues/3

**Comment by pesseyjulien** [comment]
Great, did not see this before, as you could guessed ! :)

Thanks !
